SELECT count(*) as FISH_COUNT ,c.FISH_NAME
FROM (
    SELECT a.*, b.FISH_NAME
    FROM FISH_INFO a
    INNER JOIN FISH_NAME_INFO b
    ON a.FISH_TYPE = b.FISH_TYPE
) c
GROUP BY c.FISH_NAME
ORDER BY FISH_COUNT DESC;