spring:
  application:
    name: week2
  config:
    import: optional:application-secret.properties
  jpa:
    hibernate:
      ddl-auto: none # 실제 서버에서 사용시 모든 데이터가 다 날아가므로 주의
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
  jwt:
    secret: b0e36a1dda45e3193143c586be97cd26a6af7d647de442d16809c4f6464f31329017c965cf435