-- 코드를 입력하세요
SELECT b.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (
    SELECT half.*, info.INGREDIENT_TYPE
    FROM FIRST_HALF half
    INNER JOIN ICECREAM_INFO info
    on half.FLAVOR = info.FLAVOR
) b
GROUP BY b.INGREDIENT_TYPE;